FROM public.ecr.aws/lambda/python:3.8

RUN yum install -y python3 python3-pip
# RUN yum install -y chromium-browser

COPY requirements.txt requirements.txt
RUN python3 -m pip install -r requirements.txt
RUN python3 -m pip install awscli --upgrade --user

COPY ./Modules   ./Modules


ENV AWS_ACCESS_KEY_ID=AKIAVTWL6PT5PMSLZ6KP
ENV AWS_SECRET_ACCESS_KEY=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
ENV AWS_DEFAULT_REGION=sa-east-1


COPY headless-chromium ./
COPY chromedriver   ./
COPY app.py   ./

RUN curl https://intoli.com/install-google-chrome.sh | bash
CMD ["app.handler"]      